### ISSUE TITLE
Make APK available for testing outside of the Play store

### ISSUE THREAD

**Issue by smit1678** [hotosm/sente-finder#37]
@benjaminug Is there a pre-built APK available and can we add it to the repo here? I've attempted to get this project working locally but it seems to fail to build.

**Comment by benjaminug** [comment]
@smit1678 Find the apk here: https://github.com/hotosm/sente-finder/blob/master/APK/sente-finder-v18.apk

We shall continuously update [this ](https://github.com/hotosm/sente-finder/blob/master/APK/)directory with the latest APK
